### ISSUE TITLE
Reduce travis builds and/or reduce rate limit usage

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1077]
Now that we have an even larger team, it is more likely that we will be running into rate limits with travis. One possible way to reduce the occurrence of rate limiting is by stopping travis from doing builds when we merge into develop, since this is redundant because of the testing we do for the PR. Should check if it is possible to either stop builds for a given branch or within the travis script to see if it is a develop merge and skip the testing.

**Comment by coverbeck** [comment]
I could be wrong, but I don't think it's always redundant to run  builds on merges into develop. If two PRs are merged into develop at almost the same time, then each PR may not have the other's changes, and it's possible an error might occur when the two PRs interact with each other.

**Comment by denis-yuen** [comment]
Brainstorming here:
The underlying cause is that our tests are hitting rate limits, while refactoring some of this code, I noticed that we can cut down on rate limit by using the github api in more efficient ways as well. For example, we might be able to take advantage of the tree call ( https://api.github.com/repos/ICGC-TCGA-PanCancer/Seqware-BWA-Workflow/git/trees/master ) as well rather than looking for files individually

**Comment by coverbeck** [comment]
In case you haven't seen it: https://docs.travis-ci.com/user/customizing-the-build/#Limiting-Concurrent-Jobs

**Comment by denis-yuen** [comment]
Yeah, we've given it a shot in the past and I've turned it back on. 
We do have to approach the problem on both ends though, we can get a real backlog if too many builds are submitted and I do suspect we've somewhat wasteful with the rate limits we do have

**Comment by denis-yuen** [comment]
Merging with #140 
I think one good idea from there is just to make it more obvious when we hit a rate limit rather than show unrelated error messages. It should be possible to query the limit before each set of tests

**Comment by denis-yuen** [comment]
Currently done
