### ISSUE TITLE
WDL tool/workflows return wrong descriptor type in GA4GH endpoints

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1109]
### Expected behaviour
Return "WDL" as the descriptor-type in ToolVersion if the tool/workflow is WDL

### Actual behaviour
Always returns "CWL" instead

### Steps to reproduce the behaviour 
Use https://dockstore.org:8443/static/swagger-ui/index.html#/GA4GH/toolsIdGet with a WDL tool/workflow

**Comment by denis-yuen** [comment]
Seems fixed with `curl -X GET "https://staging.dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FDockstoreTestUser%2Fdockstore-whalesay%2Fdockstore-whalesay-wdl" -H "accept: application/json"`
and 
`curl -X GET "https://staging.dockstore.org:8443/api/ga4gh/v2/tools/quay.io%2Fbriandoconnor%2Fdockstore-tool-md5sum" -H "accept: application/json"`
