### ISSUE TITLE
UI doesn't handle $include (register tool)

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#1150]
## Bug Report

Dockstore interface doesn't support `$include`, `$import` and `$mixin` to populate sections.

I've used it in the doc section:

```cwl
doc:
  $include: includes/doc.yml
```

Example [here](https://github.com/cancerit/dockstore-cgpmap/tree/de3df868952b1c6e8f169d0759cc22b312a1fa31)

```
$ cwltool --validate cwls/cgpmap-bamOut.cwl 
/.../cwltool 1.0.20180130110340
Resolved 'cwls/cgpmap-bamOut.cwl' to 'file:///.../dockstore-cgpmap/cwls/cgpmap-bamOut.cwl'
...
Tool definition is valid
```

Output generated after pre-processing:

```
$ cwltool --print-pre cwls/cgpmap-bamOut.cwl | grep -F '"doc"'
    "doc": "![build_status](https://quay.io/repository/wtsicgp/dockstore-cgpmap/status)\nA Docker container for the CGP BWA-mem mapping flow. See the [dockstore-cgpmap](https://github.com/cancerit/dockstore-cgpmap) website for more information.\n",
```

### Expected behaviour

Should load the data from the additional yaml file.

### Actual behaviour

Interface can't find doc tag and raises the warning:

```
No description associated with this tool
```

### Steps to reproduce the behaviour 

See above

### Environment (Browser or OS and Dockstore version)

UI 2.0.3

**Comment by denis-yuen** [comment]
I think we'll need to review the refresh code, I think we're handling include, but its possible we're only handling it properly in a different section. 

`$include` and `$import` make sense to me since they are included in and just seem to be aliases of each other http://www.commonwl.org/v1.0/CommandLineTool.html#Document_preprocessing and http://www.commonwl.org/v1.0/Workflow.html#Document_preprocessing 

I'm a bit puzzled as to the meaning of `$mixin` and why it only appears in the schema salad specification but not the CWL specifications

**Comment by keiranmraine** [comment]
`$include` and `$import are slightly different.

`$include` attaches a simple string value only:

```cwl
doc:
  $include: includes/doc.yml

# becomes:
doc: "my documentation from the file\n even if we have lots of messy formatting"
```

`$import` attaches a key and value to an entry:

```cwl
thing:
  $import: imports/thing.yml

# becomes
thing:
  key: value
```

(I think this is correct, possible that the import requires it to be an array rather than named entity)

**Comment by denis-yuen** [comment]
Adding support for `$include` for description in the upcoming hotfix (is going to need a webservice update deployed to staging)

**Comment by garyluu** [comment]
Mostly works, created another issue for special case.  https://github.com/ga4gh/dockstore/issues/1188
