### ISSUE TITLE
Setting cwl test parameter in versions tab edit link not reflected to info when version selected

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#1230]
## Bug Report

Creating a new version of a tool where you've moved the json example and then selecting the new version as default doesn't update the location of the cwl example test file in the Info tab

### Expected behaviour

Changing the CWL/Json paths in a version and then selecting a version as default should result in the new paths being applied to the Info area.

### Actual behaviour

Old paths remain.

### Steps to reproduce the behaviour 

Create a new version of a tool with new path to json example
After setting the new path select the new version as default
Select the info tab to find no update.

... related, should changing the 'launch with' drop down also change the paths?

### Environment (Browser or OS and Dockstore version)

Chrome (OSX)

**Comment by denis-yuen** [comment]
@agduncan94  may have been resolved in staging, check this out to find out its state

**Comment by agduncan94** [comment]
The info tab paths do not refer to the paths of the default version, but rather the default paths set for the overall tool. Therefore they will not change if you change the currently selected version or the default version.

We should make it more obvious that this is the case.

**Comment by agduncan94** [comment]
Rereading this, I better understand the situation. The answer is that we don't want to force this use case on the user. It may be that they do not want the default version to change the default paths for new versions. Instead we will better document what exactly a default version is and what happens when you change the default version.

Your original issue should be dealt with once we add a Dockstore.yml feature.
