### ISSUE TITLE
Better message when web service is down

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1321]
### Desired behaviour

Currently, if the web service is entirely down, we get
```
 The webservice encountered an error trying to create/modify.

[HTTP 0] Unknown Error: [object ProgressEvent]
```

Should probably be something like

`The webservice is currently down, possibly due to load. Please wait and retry later` or similar.

**Comment by agduncan94** [comment]
Is this error visible in the UI?

**Comment by garyluu** [comment]
FYI, if the webservice is down and somebody reloads the UI2 site, the site currently redirects to the maintenance page.  However, if the page was already open, it will not redirect.  This is because in the UI2, currently there's only one endpoint that's checked to see if webservice is down.  That endpoint only runs once per page reload.

**Comment by denis-yuen** [comment]
@agduncan94  Yup, this is in the later situation. I see this message on either my-tools/my-workflows refresh if I bring the webservice down after loading the page

**Comment by denis-yuen** [comment]
Works locally now anyway
