### ISSUE TITLE
Integration tests with partial results from APIs

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#140]
We need to make the integration tests more robust by:
- making them less rate hungry
- possibly tied with making refresh more optimal
- fail with more obvious errors when rate limits are reached (currently, we get partial results which manifest in weird ways)

**Comment by denis-yuen** [comment]
Interesting note: the mylyn github api does include calls to determine remaining requests and get the limit. We may be able to use this to throw more obvious errors when rate limited.

**Comment by agduncan94** [comment]
We have made tests less rate hungry by pre populating some data.

Since the rate limit is being reached more often for tests now that we split up travis to do two jobs, we should make it higher priority to better deal with rate limits. We should investigate how the webservice could check rate limit for the current user and warn the user (or webservice) when it is reached (or almost reached).

**Comment by denis-yuen** [comment]
Yes, I would think that in the unlikely case that a regular end-user hits a rate limit, they would also find this generally useful, not just for tests. We may be able to throw a specific rate limit exception that will be more obvious in our test output.
