### ISSUE TITLE
Dockstore build to autogenerate openapi that is Smart API compliant

### ISSUE THREAD

**Issue by achave11** [ga4gh/dockstore#1464]
### Smart-api compliance 
Current implementations of the swagger code generator and the transformer to openapi schemas is incompatible with smart-api standards. The issue seems to be an additional tag in swagger called position, which according to swagger docs was deprecated after `1.5.x` 
**Smart-Api:** http://smart-api.info/

#### NOTES:
* Currently **`openapi.yml`** schemas gets build by `swagger2openapi` tool.
* More tags need to be added to **`openapi.yml`** for it to be smart-api compliant.

#### Problems:
* 'swagger2open' does not generate correct format due to a not supported `position` tag/parameter.

#### Solutions:
* Using `sed` to remove position tag from **`openapi.yml`** while maven builds project.
* Manually modify `openapi.yml` file to include required tags, as well as removing the position generated by translator `swagger2open` tool.
* Additional `-NIHdatacommons` tag need to be added to the list of tags in the schemas document.
   * Not generated when modifying `Descriptions.java` under _dockstore-webservice_ dependency.
* Additional `-termsOfService` tag need to be added to the list of tags in the schemas document.
   * Generated by modifying `Descriptions.java`
* Additional `-x-role` tag need to be added to the list of tags in the schemas document.
   * Not compatible with `SwaggerDefinitions` can not be included in swagger generator.
* Additional `-x-url` tag need to be added to the list of tags in the schemas document.
   * Not compatible with `SwaggerDefinitions` can not be included in swagger generator.
* Additional `-x-type` tag need to be added to the list of tags in the schemas document.
   * Not compatible with `SwaggerDefinitions` can not be included in swagger generator.

┆Sprint: Lighthouse Sprint 28 Blue Gum
┆Issue Number: DOCK-16

**Comment by coverbeck** [comment]
@denis-yuen How about if we add <skip></skip> to the exec-maven-plugin section running swagger2openapi, then change .travis.yml to set the property so that Travis never runs that plugin? We could then do the transformation of the openapi with another execute; removing the position property, and adding any tags.

Otherwise, could you expand on your idea of running a service to do this? I'm not clear where the service would live.

**Comment by denis-yuen** [comment]
re: service
I had in mind somewhere outside the regular build process due to the propensity for npm to fail but also because of the lack of a Maven plugin for swagger2openapi. 

I had a few ideas for investigation for a replacement
1) Call an online converter (and avoid failing when not available) like the API at https://mermade.org.uk/openapi-converter 
2) Use the existing npm swagger2openapi distribution, but as a cron task or similar https://docs.travis-ci.com/user/cron-jobs/ (not sure if there is enough configuration options to allow for this)
3) A hubot plugin or a cron task on the hubot host

Putting the swagger2openapi behind a profile or similar so that travis avoids running it would be a partial solution, it still annoys me that we have a dependency on npm for a Maven project.

**Comment by coverbeck** [comment]
For the first one, do you mean calling the the online converter as part of the Maven build?

**Comment by denis-yuen** [comment]
Could be, I think its worth investigation either in the build process or as a service/cron

**Comment by achave11** [comment]
## Smart-Api Dockstore Tool Registry Service has been registered. 
#### [smart-api](http://smart-api.info/ui/2d4db082ffe554906c92f8cdda1db501)
#### [hosted-schemas](https://github.com/achave11/tool-registry-service-schemas/blob/dockstore/smart-api/src/main/resources/swagger/openapi.yaml)
The approach taken was very viable. Taking the `ga4gh/tool-registry-service-schemas` and adapting it to the purposes of dockstore. Changes included:
* Adding additional tags to satisfy the smart-api requirements.
* Adding server-url pointing to dockstore-api

**Comment by denis-yuen** [comment]
@coverbeck  would it be correct to say that the current approach is sufficient and that this ticket can be closed pending a future need for a more automated approach?

**Comment by coverbeck** [comment]
@denis-yuen The current approach is sufficient for Smart API. But @achave11 was pretty close to implementing an approach from this ticket, so he is wrapping it up and will submit a PR today or tomorrow. Although we don't need it for Smart API, it might be useful to have the generated openapi.yaml being valid for some future use.

Do you want to take a look at Abraham's PR and decide then whether to accept it or not, and then close this bug accordingly?

**Comment by denis-yuen** [comment]
Merged in, thanks @achave11

**Comment by cricketsloan** [comment]
➤ Abraham Chavez commented:

https://github.com/ga4gh/dockstore/pull/1503 ( https://github.com/ga4gh/dockstore/pull/1503 )
