### ISSUE TITLE
Add entry tooltips do not work

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1496]
This is due to bootstrap and angular material not playing nicely together. We should convert the modals from bootstrap to material and then add material tooltips.

**Comment by denis-yuen** [comment]
Hmm, bumping priority of this

**Comment by denis-yuen** [comment]
![screenshot from 2018-08-22 15-45-20](https://user-images.githubusercontent.com/1730679/44486775-89744f00-a622-11e8-81dd-d147425eb768.png)

A few issues to address
1) Error for subsequent inputs seems to flow together, making it unreadable
2) Dockstore is allowed to be a Source control type for source control provider. This is probably my bad due to the fix for a blank source control provider in https://github.com/dockstore/dockstore-ui2/pull/410 
A fix would need to retain the ability to see/search by Dockstore workflows in search but not allow it as an option here

**Comment by agduncan94** [comment]
Source code provider and descriptor type don't seem to have tooltips for workflows. Tools modal looks fine.

**Comment by garyluu** [comment]
It's because the previous ones didn't have a tooltip and it should be self-explanatory already.  Although we could make it a rule that every form field should have a tooltip i guess

**Comment by agduncan94** [comment]
Fair enough, closing this then.
