### ISSUE TITLE
Test json link generation and launch display issues

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1548]
### Expected behaviour
The command listed under `or grab one that the workflow author has provided (if applicable) ` should have the correct TRS path in UI2.

Note: this works on staging

### Actual behaviour
The TRS path listed is https://dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2F%20%24%7B%20workflowPath)%20%7D/versions/%24%7B%20versionName%20%7D/NXT/tests

### Steps to reproduce the behaviour 
- See Dockstore.org
- https://dockstore.org/workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2:dockstore?tab=info

 DockstoreAPI - 1.4.4
DockstoreUI - 2.1.4 

Also 

### Expected behaviour
Should hide Launch With Firecloud for workflows with secondary descriptors?
@coverbeck is it the case that both the checker workflow and the parent should not display launch with due to their use of secondary descriptors
https://dockstore.org/workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2_wdl_checker:dockstore?tab=info
and 
https://dockstore.org/workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2:dockstore?tab=info 

### Actual behaviour

Not sure, but should add documentation on what kind of workflows (http imports, no. relative imports, no?) work with Firecloud launch-with at https://docs.dockstore.org/docs/user-tutorials/language-support/

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-32)
┆Issue Number: DOCK-32

**Comment by garyluu** [comment]
If DNAStack doesn't handle secondary descriptors imports either, should probably hide/disable that button too.

**Comment by coverbeck** [comment]
Yes, we currently do hide Launch with FireCloud if there are secondary descriptors. But as @garyluu pointed out in verifying #1372 , maybe we should disable it instead of hide, with a tooltip explaining why.

We should also update https://docs.dockstore.org/docs/user-tutorials/firecloud-launch-with/ to mention this restriction.

**Comment by garyluu** [comment]
Ok so it appears there's a bug where it's hidden most of the times, but if you go to https://dockstore.org/workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2:dockstore?tab=info and then click the checker workflow, it will appear.  Refreshing the check workflow page however, makes it disappear.

**Comment by denis-yuen** [comment]
So I have confirmation that for DNAstack, both http imports and file-based imports do not work. 

@coverbeck can I confirm that for Firecloud, while secondary/file-based imports do not work, http imports can be used since TopMed workflow seems to have them? 

@garyluu @coverbeck 
Charles, do you mind disabling the DNAstack button for all imports (with a tooltip) and Firecloud dependent on the answer above. 

Gary, please update the workflow comparison table (launch-with sections), the Firecloud tutorial, and look into the bug with the checker workflows. Thanks!

**Comment by denis-yuen** [comment]
Note to @coverbeck  and @denis-yuen 
This (being the disable/enable buttons) should go into the https://github.com/dockstore/dockstore-ui2/tree/hotfix/2.1.5 branch

**Comment by coverbeck** [comment]
I don't know how I overlooked it before, but for DNAstack we don't specify the workflow version in the url we give to them.

Since we wouldn't know which version of the workflow to check for imports for DNAstack, we will only be able to apply the disabling logic to the Launch with FireCloud button.

**Comment by coverbeck** [comment]
When you click the link to go to DNAstack, you get redirected to page where you have to pick the version. Since we don't know which version the user will select in DNAstack, I don't think we should prevent the user from navigating to DNAstack because the current version has imports, because the user may not select that version.

**Comment by denis-yuen** [comment]
I think both are fair points. But I think its reasonable to throw up a warning, whether modal or not, telling the user to expect failure if the current version is selected

**Comment by denis-yuen** [comment]
On staging.dockstore.org with 
DockstoreAPI - 1.4.5
DockstoreUI - 2.1.5

_Working_
1) Test json link generation seems fixed
2) Launch-with buttons correctly disabled on skylab workflow, working with other workflows

_Not-working_ 
1)  Buttons are enabled when first browing to a checker workflow, disabled properly after a refresh
ex: go to https://staging.dockstore.org/workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2_wdl_checker:mk-optimus-portability?tab=info , go to the parent via "view", go back to the checker workflow via "view"

**Comment by denis-yuen** [comment]
Last issue fixed with staging running with 
 
DockstoreAPI - 1.4.5
DockstoreUI - 2.1.6
