### ISSUE TITLE
Improve Performance of Shared Workflows Endpoint

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1595]
## Feature Request 
In `io.dockstore.webservice.resources.WorkflowResource#sharedWorkflows` we are fetching workflows one by one from the database via Hibernate; we should be able to improve the code to fetch all the workflows with one query.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-40)
┆Issue Number: DOCK-40

**Comment by cricketsloan** [comment]
[~rjbautis] Is it possible that Walt could review this for you or are you stalled on Charles?

**Comment by cricketsloan** [comment]
➤ Ryan Bautista commented:

[~casloan] The PR is ready to be merged since I have two approval's from Andrew and Gary, but my understanding is that I have to have Dennis approve it as well. 

I can ask Charles tomorrow if I should still wait for Dennis. If not, I can merge the PR ASAP and close the ticket.

**Comment by coverbeck** [comment]
We should wait for Denis' approval.
