### ISSUE TITLE
Export as Zip not working

### ISSUE THREAD

**Issue by kaushik-work** [ga4gh/dockstore#1864]
## Bug Report
The export as ZIP button as no effect

### Expected behaviour
ZIP bundle of all files should be downloaded by browser

### Actual behaviour
No response

### Steps to reproduce the behaviour 
Navigate to https://dockstore.org/workflows/github.com/h3abionet/h3agatk:1.0.1?tab=info and click "Export as ZIP" button.

(Any workflow/tool will do)

### Environment (Browser or OS and Dockstore version)

Describe your operating system (relevant for CLI and launcher) or your web browser (name and version, relevant for the Dockstore website) 

Chrome on macOS: Version 69.0.3497.100 (Official Build) (64-bit)

Thanks!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-428)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-428

**Comment by kaushik-work** [comment]
@agduncan94 you are right sir! The popup notification is so non-intrusive that I missed it until I was actively looking for it. Is there a way to have this do a regular file download, rather than have a popup?

**Comment by agduncan94** [comment]
@kaushik-work I also didn't notice on Chrome since they don't make the popup block obvious, it was only when I used Firefox did I notice because they had a rather large warning bar for the popup block.

It is possible there is a way to do this as a regular file download, we will have to investigate. I could see this being an issue since a lot of people use Chrome.

I think for now this is a good thing to add to our FAQ in case more people run into this issue.

**Comment by garyluu** [comment]
For whomever is going to make the fix for this: just change the #downloadZipButton button (workflow and tools) into an anchor and `[href]="downloadZipLink"` and remove the downloadZip() function

**Comment by Ldcabansay** [comment]
Verified that export to zip now works as a regular file download not a pop-up.
