### ISSUE TITLE
Update and test icgc storage client with current score client

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1949]
### Desired behaviour

The icgc storage client has been renamed and updated to Score (see https://song-docs.readthedocs.io/en/develop/score-client.html ). The current Dockstore plugin ( https://github.com/dockstore/icgc-storage-client-plugin ) has been tested with the icgc storage client 1.0.23. Update the plugin, test, and provide examples (hopefully there is one or two example data files that can be tested with when running a workflow from within Collaboratory). 

Note that the scope here is running a workflow with the Dockstore client that then invokes Cromwell or cwltool to properly provision input files. Consider pushing back output files to be a second ticket. Getting a plain WDL workflow (launched without Dockstore) to pull/push input files with something like DRS/DOS would also be out of scope.

 @andricDu or a delegate will have additional info when starting this ticket.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-293)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Issue Number: DOCK-293

**Comment by garyluu** [comment]
For things to follow up from the first PR:

- Only tested with directories that contain multiple files, can't find a reasonable size single file to download from ICGC
- Didn't change the plugin name
- Couldn't get Utilities.execute to work, had to change to something else (ProcessBuilder)
- Didn't commit my test yet, not sure how to hide my key.

**Comment by agduncan94** [comment]
Trying to run the example workflow from the https://github.com/dockstore/icgc-storage-client-plugin readme.

Getting the following error
08:57:49.950 [pool-2-thread-1] INFO io.dockstore.common.Utilities - CMD: /home/aduncan/.dockstore/plugins/dockstore-file-icgc-storage-client-plugin-0.0.6 --quiet download --object-id eeca3ccd-fa4e-57bf-9fde-c9d0ddf69935 --output-dir /home/aduncan/Documents/client-testing/cromwell-input/385671d8-554b-4d51-a037-6f8e72526ea5/icgc: --output-layout id
org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "/home/aduncan/.dockstore/plugins/dockstore-file-icgc-storage-client-plugin-0.0.6" (in directory "."): error=13, Permission denied)

**Comment by denis-yuen** [comment]
Maybe the plugin/install instructions for the plugin isn't doing the equivalent of chmod?

**Comment by garyluu** [comment]
Funny, I don't think I made a release for this

**Comment by garyluu** [comment]
Ok, made the 0.0.7 release

**Comment by agduncan94** [comment]
Got it working after I updated to the new release. Made ticket https://github.com/ga4gh/dockstore/issues/2306 for documentation purposes.

Tested on webservice 1.6.0-rc.0
