### ISSUE TITLE
Nextflow: Grab workflow descriptions

### ISSUE THREAD

**Issue by ewels** [ga4gh/dockstore#1979]
## Feature Request 
It would be great if Dockstore could auto-populate a few extra fields from Nextflow workflows which are sometimes available in the config metadata.

### Desired behaviour
Description: `manifest.description` ([example](https://github.com/nf-core/rnaseq/blob/e8376373da8c1dfb0cae5372947cf5b241056076/nextflow.config#L152))

Author (in table view): `manifest.author` ([example](https://github.com/nf-core/rnaseq/blob/e8376373da8c1dfb0cae5372947cf5b241056076/nextflow.config#L154))

Note that _**Workflow Path:** `/nextflow.config`_ is a little confusing, as the workflow is in the `main.nf` file (default filename - can be defined with `workflow.mainScript`), and it's this that you execute, rather than the config file. I know I can change it manually, but if it's pulled by default somewhere.

Apologies if these already happen, it could be that I'm simply being too impatient after clicking refresh on my GitHub repos :grinning:

Phil

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-209)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-209

**Comment by denis-yuen** [comment]
@ewels 
Thanks for trying things out. I think the first two should happen, although there are config files that don't parse properly on our end but https://dockstore.org/workflows/github.com/nf-core/vipr:master?tab=info has an example where it does. We'll look into rnaseq

The workflow path is a little confusing, we can probably change the name to something more appropriate. But the workflow path is where we start looking for a workflow (maybe more relevant for languages that can often have more than one workflow in a repo).

**Comment by agduncan94** [comment]
We should be pulling the author and description, but testing locally it looks like we are having a problem parsing the config file.

**Comment by ewels** [comment]
Thanks both, let me know if there's anything I can do (some of these `manifest` variables are relatively new to nextflow).

I understand the logic behind the workflow path, and it's not a high priority. Note that nextflow can also have multiple `.nf` workflow files in a single repo (typically `manifest.mainScript` in a `nextflow.config` should only point to one though I think - `main.nf` by default).

Phil

**Comment by agduncan94** [comment]
It looks like the issue is with our parsing code. Specifically how we deal with the Java classes referenced in the nextflow config file. As a temporary solution we simply stub the classes (ex. nextflow.util.MemoryUnit) since they are not required for parsing. This is not the best solution because if a class that is not stubbed is referenced there will be a parsing error, which is happening now with rnaseq.

The rnaseq config has the following line `return Math.min( obj, params.max_cpus as int )`. It is expecting the class java.lang.Integer, but we do not have this stubbed.

We should find a better way of dealing with this, as other classes are probably going to exist.

**Comment by denis-yuen** [comment]
There's also #1872 , specifically with the license change we have permission to borrow Nextflow code. But its going to take a bit of time to figure out how to cleanly extract the specific functionality we need from the whole Nextflow code-base.

**Comment by ewels** [comment]
Nice - this is how we do config parsing for nf-core, we use nextflow. See the code [here](https://github.com/nf-core/tools/blob/54e233a4c167f515b6f616b3c5a8a9bd660861c0/nf_core/utils.py#L11-L31). If you can run Java natively then there's probably a nicer embedded method to do it though.. (the tools package is Python and we expect people to have nextflow installed anyway).

**Comment by denis-yuen** [comment]
Oh cool, that at least gives us a good starting point. Thanks for the tip!

**Comment by denis-yuen** [comment]
We ended up calling out to Nextflow separately too
(it wasn't clear due to our lack of groovy expertise how to separate just what we needed and we didn't want to include all of Nextflow in our classpath)
May need to optimize later, but this should get us compatibility with descriptions, etc. from nf-core

Limitation: We can't use Nextflow to aid us in detecting what files are useful from a repo (i.e. in CWL, we start with the "entry"/primary descriptor and spider out to figure out what files in the repo are relevant)

**Comment by agduncan94** [comment]
Works on
DockstoreAPI - 1.6.0-rc.0
DockstoreUI - 2.3.0-rc.1
