### ISSUE TITLE
Navigating away-and-back to Files Tab for workflows throws ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by rjbautis** [ga4gh/dockstore#2004]
An ExpressionChangedAfterItHasBeenCheckedError exception is written to the console when a user navigates away and then back to a workflow's Files Tab. This exception has no affect on any of the workflow component / child-component functionalities, as far as I can tell. However, it is worth noting.

### Steps to reproduce the behaviour 
Go to local instance of Dockstore UI: http://localhost:4200/workflows/github.com/gatk-workflows/gatk4-somatic-cnvs/cnv_somatic_panel:1.1.0?tab=info

* Click on Files Tab
* Click on any other tab, such as Versions
* Click on Files Tab again

There will be an error written to the developer console originating from the LaunchWorkflowComponent.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-187)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-187

**Comment by denis-yuen** [comment]
Decision to merge, Ryan will rebase and work with Gary for the consequences

**Comment by coverbeck** [comment]
Verified in staging.dockstore.org, version 2.3.0-beta.0, that this no longer happens.

**Comment by coverbeck** [comment]
Reverified this with a local build off develop branch -- it turns out you won't see this error in Angular production mode even if there is an issue in dev mode, see the [last paragraph](https://blog.angularindepth.com/everything-you-need-to-know-about-the-expressionchangedafterithasbeencheckederror-error-e3fd9ce7dbb4), (thanks @NatalieEO) -- my previous verification was not valid.
