### ISSUE TITLE
Provide tooltip when hovering over workflow name in search results box

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#2059]
Sometimes the workflow names are too long to be fully presented in the search results box and the names are truncated. In this case the user needs a tooltip to pop up to see the full workflow name.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-211)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-211

**Comment by denis-yuen** [comment]
Also can delete Docker Pull column, but still need tooltips probably since some will still be cut-off

**Comment by garyluu** [comment]
just remembered...this was only done for the search results in the search page, but wasn't done for the home page

**Comment by david4096** [comment]
Although tooltips do appear over search results, I'm concerned we haven't presented an improvement because it still truncates at the same length as the results box.

![Screenshot from 2019-03-19 11-35-49](https://user-images.githubusercontent.com/3795586/54632617-c333f980-4a3b-11e9-99f6-ebd478f697be.png)

The name for this repository is `github.com/david4096/dockstore_workflow_cnv/aaaaaaaa333333aaaaaaaaaaaaacccccccccccccccccccccccccczzzzzzzzzzzzzzsssssssssss` which causes flow problems elsewhere too.

![Screenshot from 2019-03-19 11-47-55](https://user-images.githubusercontent.com/3795586/54633162-db584880-4a3c-11e9-8ba7-1fc8431e5088.png)

**Comment by garyluu** [comment]
https://github.com/dockstore/dockstore-ui2/pull/591/commits/87f0c0e5a68353b62a61d1bf97cba0d92c2c9521

**Comment by denis-yuen** [comment]
Looks like the tool tip goes multiline and we can see the whole name
Other flow issues can be addressed with new tickets if needed
DockstoreAPI - 1.6.0-rc.0
DockstoreUI - 2.3.0-rc.1
