### ISSUE TITLE
Tool pagination header URLs broken

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#2153]
### Expected behaviour
The header has links that are not broken

GET https://staging.dockstore.org/api/api/ga4gh/v2/tools?limit=100&offset=1 returns:

last_page: https://staging.dockstore.org/api/api/ga4gh/v2/tools?limit=100&offset=4
next page: https://staging.dockstore.org/api/api/ga4gh/v2/tools?limit=100&offset=2
self_link: https://staging.dockstore.org/api/api/ga4gh/v2/tools?limit=100&offset=1

### Actual behaviour
The header has links that are broken

GET https://staging.dockstore.org/api/api/ga4gh/v2/tools?limit=100&offset=1 returns:

last_page: https://staging.dockstore.org/api/ga4gh/v2/tools?limit=100&offset=4
next page: https://staging.dockstore.org/api/ga4gh/v2/tools?limit=100&offset=2
self_link: https://206.108.127.16/api/ga4gh/v2/tools?limit=100&offset=1

### Steps to reproduce the behaviour 
From swagger-ui do use the /tools endpoint

### Environment (Browser or OS and Dockstore version)
DockstoreAPI - 1.6.0-alpha.6
DockstoreUI - 2.3.0-alpha.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-539)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-539

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

It looks like self_link is still wrong:

curl \-v \-X GET https://staging.dockstore.org/api/api/ga4gh/v2/tools?limit=100&offset=1 ( https://staging.dockstore.org/api/api/ga4gh/v2/tools?limit=100&offset=1 )

…

< self_link: https://128.114.59.168/api/ga4gh/v2/tools?limit=100 ( https://128.114.59.168/api/ga4gh/v2/tools?limit=100 )
< next_page: https://staging.dockstore.org/api/api/ga4gh/v2/tools?limit=100&offset=1 ( https://staging.dockstore.org/api/api/ga4gh/v2/tools?limit=100&offset=1 )
< last_page: https://staging.dockstore.org/api/api/ga4gh/v2/tools?limit=100&offset=4 ( https://staging.dockstore.org/api/api/ga4gh/v2/tools?limit=100&offset=4 )

self_link should not have an IP address and it should have ‘api/api’ instead of ‘api/’

**Comment by denis-yuen** [comment]
Ah, crummy.

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

verified on DockstoreAPI \- 1.6.0-rc.0DockstoreUI \- 2.3.0-rc.1
