### ISSUE TITLE
Endpoints that don't do database access shouldn't have UnitOfWork annotation

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2302]
## Feature Request 

The `@UnitOfWork` annotation should only be present on endpoints whose implementations access the database.

When present, the annotation starts a database transaction, which requires a database connection. When contention for database pool connections gets tight (there are 32 available connections), this can slow down the endpoints, cause them to fail (if unable to get a connection soon enough), and/or also the same effect on other endpoints that do require a connection.

Off-hand, noticed 3 endpoints in MetadataResource that have but do not need the annotation. There may be more -- implementor should check.

* getSourceControlList
* getDockerRegistries
* getDescriptorLanguages

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-628)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-628

**Comment by denis-yuen** [comment]
Not sure if this is needed for @GET when there are no changes

**Comment by david4096** [comment]
The UnitOfWork annotation can be used "non-transactionally" by setting transactional to false for things that won't need to be rolled back.

Similarly, when an item is read only or if you want to set a different cache mode, it can be done using parameters to the annotation. I believe there is an advantage to keeping the annotation so that Hibernate can handle caching even for resources that don't require a write transaction.

For example, `metadata/sourceControlList` does not "need" a hibernate session in that it doesn't touch the DB. However, other endpoints that don't perform write transactions should probably get the `read-only` tag to answer @denis-yuen .

https://www.dropwizard.io/0.7.1/dropwizard-hibernate/apidocs/io/dropwizard/hibernate/UnitOfWork.html

**Comment by coverbeck** [comment]
I briefly played around with setting the read-only attribute to see if it would make a performance difference and the results were very inconclusive; sometimes the method would be faster and sometimes slower.

I think it's still a good idea to set it as appropriate though.

**Comment by denis-yuen** [comment]
It's possible the database connection isn't the [rate-limiting step](https://en.wikipedia.org/wiki/Rate-determining_step) until it outright fails. But good to know/set properly anyway

**Comment by coverbeck** [comment]
This was addressed in PR #2345

**Comment by denis-yuen** [comment]
On the other hand, this isn't really user-visible.
