### ISSUE TITLE
Can't find cwl file given a path

### ISSUE THREAD

**Issue by philloooo** [ga4gh/dockstore#266]
I was trying to create a test workflow at https://www.dockstore.org/my-workflows, my cwl file lives at [/cwl/s3upload.cwl](https://github.com/LabAdvComp/cwlutils/blob/master/cwl/s3upload.cwl). But the webpage just says it can't fine it?
![screen shot 2016-06-09 at 8 04 20 pm](https://cloud.githubusercontent.com/assets/3324084/15951413/a64d0e88-2e7d-11e6-9e04-cdc5c90974a4.png)
![screen shot 2016-06-09 at 8 04 11 pm](https://cloud.githubusercontent.com/assets/3324084/15951422/b3906540-2e7d-11e6-9a4e-8d629e0378a0.png)
![screen shot 2016-06-09 at 8 04 31 pm](https://cloud.githubusercontent.com/assets/3324084/15951434/cbd76efa-2e7d-11e6-8a8b-e2c921b3ec9d.png)

Am I doing anything wrong?
cc @briandoconnor

**Comment by denis-yuen** [comment]
Hi,
Sorry for the problems that you encountered, there's a couple of issues here. 

1. The[ CWL file](https://github.com/denis-yuen/cwlutils/blob/master/cwl/s3upload.cwl#L19) you're trying to register is not actually a workflow, but is in fact a CommandLineTool. You should work with it as a tool rather than as a workflow 

2. There's an outstanding issue at #224 . In short, when using cwl files in a different location, you'll need to set the path via CLI. You'll need to run something like the following command `dockstore tool update_tool --entry quay.io/LabAdvComp/s3cwl --cwl-path /cwl/s3upload.cwl --wdl-path /wdl/s3upload.wdl` to get refresh to work properly. 

I've created an example of what the result should look like at https://www.dockstore.org/containers/quay.io/denis_yuen/s3cwl (I can take this down after you've taken a look). 

Hope that helps!

**Comment by philloooo** [comment]
Thanks denis! It worked after I change the path to cwl/example_workflow.cwl, without using the cli.
