### ISSUE TITLE
Descriptor and Dockerfile line numbers

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#317]
Display these to aid with debugging in the GUI

**Comment by jpatricia** [comment]
The current one in the repo will not work if the line is too long and goes to the next line, will look like line 5-6:
![screenshot from 2016-08-12 17 50 55](https://cloud.githubusercontent.com/assets/6503391/17638069/b22b12ee-60b5-11e6-8c3b-e3195a634579.png)
it's supposed to stay as line 5 instead of being line 6
So will probably try to use a library..
Tried this library: https://github.com/wcoder/highlightjs-line-numbers.js, but it gave the same result as the current version in the repo
Another library that can be tried: https://github.com/mikemiles86/reveal-line-numbers

**Comment by denis-yuen** [comment]
Functional on staging.dockstore.org
