### ISSUE TITLE
Contact Author / Request Access

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#41]
This is a two-for-one, I'd like a button for all registered images that says "Contact Author" if the author has provided an email.  It then just does a mailto with information pre-filled in the subject line, something like "Dockstore.org contact request about <image name>".

The second feature is, again if the author provided an email, for private repos a link for "Request Access" that simply emails the author with a simple mailto where the subject is "Dockstore.org request for access to <image name>".  And the body can have something like:

```
I would like to request access to your Docker image <image name> housed on <Quay.io/Dockerhub/etc>.  My username on <Quay.io/Dockerhub/etc> is <username>.
```

This will facilitate users getting access to private repositories for those where we can't directly do this through an API.

**Comment by oicr-vchung** [comment]
Button has been added, require changes to the web service to display the author's e-mail address. Quay.io requires admin-level scope permissions to return an e-mail address. GitHub and Bitbucket require user-level permissions (the e-mail can be cached at account linking time).

There are three obvious ways to return an e-mail address for a Dockstore image:

* Get it from the image registry: Doesn't work for Docker Hub, but this makes the most sense, since the permissions are tied to the registry
* Get it from the Git repository through an API call: Minimally-invasive, images are built from Dockerfiles on the Git Repository
* Request it from the user through the UI

**Comment by denis-yuen** [comment]
I think the second should be sufficient. We want to avoid admin-scope permissions for something like this (although I find it a bit surprising that you need admin-scope). The email addresses tied to the user's github account should be sufficient and might even be more up-to-date than quay.io.
