### ISSUE TITLE
Tool and workflow deletion

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#655]
### Desired behaviour

Users should have the ability to delete their own tools and workflows.
Alternatively, to switch the Build Mode
Note that we already have "deregister" for manually registered tools. 

We ran into this when debugging tools that were registered as manual before build triggers were added to the underlying repos. 

### Environment (Browser or OS and Dockstore version)
1.1.5

**Comment by agduncan94** [comment]
After putting more thought into the idea of a delete button instead of a restub, and having the workflow disappear until the next refresh, I am starting to not like the idea.

A user might get annoyed if they delete a tool and then it comes back suddenly next time they refresh.

The main purpose we thought of was that a user wanted to completely reset a workflow, just in case they configured something wrong.

Perhaps updating the existing restub code to remove all extra data from the workflow, and just create a blank workflow with only the necessary defaults selected. Pretty much make it do the same thing as deleting the workflow and refreshing, but now the user won't see the tool randomly appear.

Also, we should more obviously indicate if a workflow is a stub or not on the my workflows page.

**Comment by garyluu** [comment]
Not entirely related, but if we keep the stubbing feature, it might be useful to have a filter checkbox in the left panel somewhere that automatically hides all the stubbed workflows from the panel(s).   This is in the event that the user has a bunch of github organizations that are unneeded.

**Comment by denis-yuen** [comment]
I think the problem is that there are two scenarios that someone would want to delete it. 
1) The stub is totally irrelevant and they just want to delete it permanently. 
2) The workflow was configured in a crummy way and it would be easier to delete it and restart. 

I think unstub makes sense for both if we don't switch to a dockstore.yml. I think delete makes more sense for both when we do switch to a dockstore.yml. 

Since the issue is essentially broken up into two parts, tools and workflows, maybe we can tackle this in two phases. 

1) Add delete across the board for tools since the re-appearing problem doesn't occur there
2) Close/rename the tickets having to do with tool delete
3) Reschedule a closer look at workflow deletion at a time closer to the next release when we've decided on dockstore.yml

**Comment by agduncan94** [comment]
Just noting that I have added 1. Delete tools across the board

**Comment by denis-yuen** [comment]
See also #1995
