### ISSUE TITLE
Use GitHub Search API to detect repos with CWL files rather than create stubs

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [ga4gh/dockstore#729]
## Feature Request

Originally, I added my workflows manually.

Then I clicked the "Refresh All Workflows" and then in dockstore I saw a listing of every github org I'd been a part of:
![extra_orgs_in_dockstore](https://cloud.githubusercontent.com/assets/10213802/26222906/c6a8bbb2-3be9-11e7-9927-79b0882d48d4.png)

Needless to say, this is a rather large listing, and when some organizations have many repos, it's hard to find the right one. Is there a way to get rid of this clutter so I can *only* see the workflows I've added manually? I'd say about > 90% of the repos I have access to do not have any CWL in them so it's not really necessary for them to be here.

**Comment by denis-yuen** [comment]
Note, this is due to Dockstore creating a stub entry for every possible repo you have. 
You can subsequently choose the stub entry that you wish to refresh and upgrade to a proper workflow. 
We can't actually look for CWL files due to rate limit issues. 

This can be improved if we can use a GitHub search API or similar to find likely repos with CWL files in them.

**Comment by denis-yuen** [comment]
We're more likely to go down the https://github.com/ga4gh/dockstore/issues/1105 route
