### ISSUE TITLE
"Launch with" snippet does not work for Workflows

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [ga4gh/dockstore#844]
## Bug Report

The main page for a workflow contains as snippet of "Launch with" code that looks like this:
```bash
# alternatively, cwltool can run a workflow directly when all inputs and outputs are available on the local filesystem
$ cwltool --non-strict https://dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/develop/plain-CWL/descriptor Dockstore.json
```
The URL generated for this snippet (or maybe the API behind it?) does not work.

### Expected behaviour

Users expect to be able to execute that code and have the workflow run.

### Actual behaviour

Error 500.

Navigate to "https://dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/develop/plain-CWL/descriptor" in your browser and you will see:

```JSON
{
"code": 500,
"message": "There was an error processing your request. It has been logged (ID 7099a2c2b9db6b63)."
}
```

### Steps to reproduce the behaviour 

Copy and paste the second "Launch with..." snippet of code for a workflow, and try running it.

This was originally reported by Chen, on Junjun's team.

@garyluu also did a quick test and seems to think that this feature works for fine tools, but not for workflows.

**Comment by garyluu** [comment]
Currently, it would fail for all workflows in UI2 because the launch workflow service is not present (the workflow component is using the launch tool service which will not work).  

For production, apparently it works for workflows without a workflow name

**Comment by garyluu** [comment]
Update:  This seems to affect...

- Tools with a tool path on both production and with UI2 because the UIs are giving the wrong URL
- Workflows with a workflow path on both production and with UI2 because of the webservice discarding the workflow name

**Comment by garyluu** [comment]
This appears to be fixed in my Aug 1 pull request.  Tested with:
- http://<ip>:8080/api/ga4gh/v1/tools/quay.io%2Fwtsicgp%2Fdockstore-biobambam2%2Fbamtofastq/versions/1.0.0/plain-CWL/descriptor
- http://<ip>:8080/api/ga4gh/v1/tools/%23workflow%2Fdenis-yuen%2Fhello-dockstore-workflow%2Fhello-world/versions/testCWL/plain-CWL/descriptor

These are shown by the launch cwltool command with tools from the backup_db.sql.  Both entries have an entry name without a corresponding entry that doesn't have an entry name (quay.io/wtsicgp/dockstore-biobam2 and denis-yuen/hello-dockstore-workflow does not exist).

**Comment by denis-yuen** [comment]
This seems present (or a similar error) on staging.dockstore.org
Go to https://staging.dockstore.org/workflows/ICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow and the launch with instructions have the following issue
```
~$ cwltool --non-strict https://staging.dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/feature%2Finclude_qa_checks/plain-CWL/descriptor Dockstore.json
/usr/local/bin/cwltool 1.0.20170828135420
Tool definition failed initialization:
https://staging.dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/feature%2Finclude_qa_checks/plain-CWL/descriptor:17:13: (u'https://staging.dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/feature%2Finclude_qa_checks/plain-CWL/PreprocessedFilesType.yaml', HTTPError(u'404 Client Error: Not Found for url: https://staging.dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/feature%2Finclude_qa_checks/plain-CWL/PreprocessedFilesType.yaml',))
dyuen@odl-dyuen2:~$ cwltool --non-strict https://staging.dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/develop/plain-CWL/descriptor Dockstore.json
/usr/local/bin/cwltool 1.0.20170828135420
Tool definition failed initialization:
https://staging.dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/develop/plain-CWL/descriptor:17:13: (u'https://staging.dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/develop/plain-CWL/PreprocessedFilesType.yaml', HTTPError(u'404 Client Error: Not Found for url: https://staging.dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2FICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow/versions/develop/plain-CWL/PreprocessedFilesType.yaml',))

```

**Comment by garyluu** [comment]
The main descriptor is `.../plain-CWL/descriptor`

The secondary descriptor (PreprocessedFilesType.yaml) is supposed to be `.../plain-CWL/descriptor/PreprocessedFilesType.yaml` but cwltool is looking for it in `.../plain-CWL/PreprocessedFilesType.yaml` since it thinks `.../plain-CWL/` is the parent directory.

**Comment by denis-yuen** [comment]
* might be fixed, but might just be misremembering
* could be either a PR to cwltool or a change to TRS schema
* check with current versions of cwltool to see

**Comment by garyluu** [comment]
Issue still present with cwltool version 1.0.20170828135420.   cwltool treats the URL like a file system path and will try to look for the other files relative to the parent of the descriptor which is /plain-CWL

Testing with OxoG and bypassing the /descriptor endpoint by using /descriptor/%2Foxog_varbam_annotate_wf.cwl directly reveals another issue possibly with our refresh code.  cwltool looks for vcf_merge_util.js because that file and relative path is mentioned in the root descriptor.  However, it appears Dockstore saved that vcf_merge_util.js as ./vcf_merge_util.js instead.  As a result, even bypassing /descriptor endpoint does not work.

**Comment by garyluu** [comment]
Looks like what was agreed upon is to just modify the cwltool launch command in dockstore-ui2 to use relative paths endpoint with the main descriptor as the path parameter

**Comment by denis-yuen** [comment]
Yup, and to make it discover-able using ga4gh endpoints only.

**Comment by garyluu** [comment]
In addition to this.  A new GA4GH endpoint will be required to display the list of available file paths for both test parameter files and descriptors.  The endpoint will be .../{type}/filePaths which will return an array of a new object definition that is {"path": string, "fileType": FileType} where FileType is a new string enum definition that is: { TEST_FILE, PRIMARY_DESCRIPTOR, SECONDARY_DESCRIPTOR }

**Comment by agduncan94** [comment]
This seems to work with webservice DockstoreAPI - 1.4.0-rc.1 and UI2 DockstoreUI - 2.1.0-rc.0
