### ISSUE TITLE
Unique 'path' in 'workflow' table

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#904]
### Desired behaviour
Make the workflow table's 'path' column have a unique constraint so that the workflow can easily be queried using path.

**Comment by denis-yuen** [comment]
@agduncan94  might go well with the adding of the source control to the workflow id work

**Comment by agduncan94** [comment]
Would it also make sense to do this for tools?

**Comment by denis-yuen** [comment]
Yup

**Comment by agduncan94** [comment]
While adding a unique constraint for paths, we realized that they do not have the not null modifier. The path should have the not null modifier, since all entries should have a path.

Currently we set the path right after creating an entry (I'm pretty sure), but we should really set it when an entry is created.

We should add a not null modifier to tool and workflow paths, and also ensure that the path is being set when the entry is created.

**Comment by agduncan94** [comment]
There seems to be a disconnect of what the paths represent. For tools, it seems like sometimes we expect them to not include the toolname, but other times we do. For example, the getPath function in Tool.java does not use the toolname, and also the findByToolPath function takes in a path and a toolname, implying that the toolpath is a different concept than the path.

If we were to add a unique constraint for paths, this would assume that no two tools have the same path. However if we consider paths where the toolname is not included, this means that you can't register two tools which have the same registry/namespace/name, but different toolnames.

**Comment by agduncan94** [comment]
We have decided on removing path from the database, as it is redundant and can be generated on the fly from other fields in the tool and workflow table. It seems like for this change to occur we mostly just have to update the ToolDAO.java and WorkflowDAO.java to be able to split up a path into the correct fields.

**Comment by denis-yuen** [comment]
Too general, will review as a part of other work
