### ISSUE TITLE
Workflow Search Filters 

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#915]
## Feature Request 
Currently there are several tool filters in the search page, but there are very few filters applicable to workflows.

### Desired behaviour
Add workflow filters (e.g. organization) to the search page.

**Comment by denis-yuen** [comment]
Also ensure that ones that should apply to both like labels, authors, and verification just work.

**Comment by denis-yuen** [comment]
As an update: this is partially testing to ensure that labels, authors, and verification work for workflows, but this is also implementation for organizations. Currently, the Organization facet only shows tool organizations but I'd also like to see it include workflow organizations in order to allow users to drill down by tool organization as well as workflow organization

**Comment by denis-yuen** [comment]
Better, needs follow-up. See #1245
